package com.heaven7.java.data.mediator.internal;

/**
 * <p>This class is generated by Data-mediator framework. DON'T EDIT IT!!!</p>
 *  @author heaven7 */
public final class SharedProperties_2 {
  static {
    SharedProperties.putToCache("java.lang.String", "testItem2_2", 0);
    SharedProperties.putToCache("java.lang.String", "testItem2_3", 2);
    SharedProperties.putToCache("com.heaven7.plugin.idea.data_mediator.test.TestParcelableData", "testItem2_6", 0);
    SharedProperties.putToCache("boolean", "testItem2_4", 0);
    SharedProperties.putToCache("java.lang.String", "test_self4_1", 0);
    SharedProperties.putToCache("boolean", "test_1", 0);
    SharedProperties.putToCache("java.lang.String", "test_self5_1", 0);
    SharedProperties.putToCache("java.lang.String", "testItem3", 0);
    SharedProperties.putToCache("int", "testItem2_5", 0);
    SharedProperties.putToCache("com.heaven7.plugin.idea.data_mediator.test.Student", "testItem2_1", 0);
    SharedProperties.putToCache("java.lang.String", "test_2", 0);
  }
}
