package com.heaven7.test;

import com.heaven7.java.base.util.SparseArray;
import com.heaven7.java.base.util.Throwables;
import com.heaven7.java.data.mediator.BaseMediator;
import com.heaven7.java.data.mediator.ListPropertyEditor;
import com.heaven7.java.data.mediator.PropertyInterceptor;
import com.heaven7.java.data.mediator.SparseArrayPropertyEditor;
import com.heaven7.java.data.mediator.internal.DataMediatorDelegate;
import com.heaven7.plugin.idea.data_mediator.test.Student;
import com.heaven7.plugin.idea.data_mediator.test.TestParcelableData;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.UnsupportedOperationException;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>This class is generated by Data-mediator framework. DON'T EDIT IT!!!</p>
 *  @author heaven7 */
public class TestItem2_$Proxy extends BaseMediator<TestItem2> implements TestItem2 {
  public TestItem2_$Proxy(TestItem2 base) {
    super(base);
  }

  public String getTestItem2_2() {
    return _getTarget().getTestItem2_2();
  }

  public TestItem2 setTestItem2_2(String testItem2_21) {
    TestItem2 target = _getTarget();
    String oldValue = target.getTestItem2_2();
    if(_getEqualsComparator().isEquals(oldValue, testItem2_21)) {
      return this;
    }
    target.setTestItem2_2(testItem2_21);
    dispatchValueChanged(PROP_testItem2_2, oldValue, testItem2_21);
    return this;
  }

  public List<String> getTestItem2_3() {
    return _getTarget().getTestItem2_3();
  }

  public TestItem2 setTestItem2_3(List<String> testItem2_31) {
    TestItem2 target = _getTarget();
    List<String> oldValue = target.getTestItem2_3();
    if(_getEqualsComparator().isEquals(oldValue, testItem2_31)) {
      return this;
    }
    target.setTestItem2_3(testItem2_31);
    dispatchValueChanged(PROP_testItem2_3, oldValue, testItem2_31);
    return this;
  }

  public ListPropertyEditor<? extends TestItem2, String> beginTestItem2_3Editor() {
    TestItem2 target = _getTarget();
    List<String> values = target.getTestItem2_3();
    if(values == null) {
      values = new ArrayList<>();
      target.setTestItem2_3(values);
    }
    return new ListPropertyEditor<TestItem2,String>(target, values, PROP_testItem2_3, this);
  }

  public TestParcelableData getTestItem2_6() {
    return _getTarget().getTestItem2_6();
  }

  public TestItem2 setTestItem2_6(TestParcelableData testItem2_61) {
    TestItem2 target = _getTarget();
    TestParcelableData oldValue = target.getTestItem2_6();
    if(_getEqualsComparator().isEquals(oldValue, testItem2_61)) {
      return this;
    }
    target.setTestItem2_6(testItem2_61);
    dispatchValueChanged(PROP_testItem2_6, oldValue, testItem2_61);
    return this;
  }

  public boolean isTestItem2_4() {
    return _getTarget().isTestItem2_4();
  }

  public TestItem2 setTestItem2_4(boolean testItem2_41) {
    TestItem2 target = _getTarget();
    boolean oldValue = target.isTestItem2_4();
    if(_getEqualsComparator().isEquals(oldValue, testItem2_41)) {
      return this;
    }
    target.setTestItem2_4(testItem2_41);
    dispatchValueChanged(PROP_testItem2_4, oldValue, testItem2_41);
    return this;
  }

  public boolean isSelected() {
    return _getTarget().isSelected();
  }

  public TestItem2 setSelected(boolean selected1) {
    TestItem2 target = _getTarget();
    boolean oldValue = target.isSelected();
    if(_getEqualsComparator().isEquals(oldValue, selected1)) {
      return this;
    }
    target.setSelected(selected1);
    dispatchValueChanged(PROP_selected, oldValue, selected1);
    return this;
  }

  public String getName() {
    return _getTarget().getName();
  }

  public TestItem2 setName(String name1) {
    TestItem2 target = _getTarget();
    String oldValue = target.getName();
    if(_getEqualsComparator().isEquals(oldValue, name1)) {
      return this;
    }
    target.setName(name1);
    dispatchValueChanged(PROP_name, oldValue, name1);
    return this;
  }

  public int getXxx1() {
    return _getTarget().getXxx1();
  }

  public TestItem2 setXxx1(int xxx11) {
    TestItem2 target = _getTarget();
    int oldValue = target.getXxx1();
    if(_getEqualsComparator().isEquals(oldValue, xxx11)) {
      return this;
    }
    target.setXxx1(xxx11);
    dispatchValueChanged(PROP_xxx1, oldValue, xxx11);
    return this;
  }

  public List<String> getDesc() {
    return _getTarget().getDesc();
  }

  public TestItem2 setDesc(List<String> desc1) {
    TestItem2 target = _getTarget();
    List<String> oldValue = target.getDesc();
    if(_getEqualsComparator().isEquals(oldValue, desc1)) {
      return this;
    }
    target.setDesc(desc1);
    dispatchValueChanged(PROP_desc, oldValue, desc1);
    return this;
  }

  public ListPropertyEditor<? extends TestItem2, String> beginDescEditor() {
    TestItem2 target = _getTarget();
    List<String> values = target.getDesc();
    if(values == null) {
      values = new ArrayList<>();
      target.setDesc(values);
    }
    return new ListPropertyEditor<TestItem2,String>(target, values, PROP_desc, this);
  }

  public int[] getXxx4() {
    return _getTarget().getXxx4();
  }

  public TestItem2 setXxx4(int[] xxx41) {
    TestItem2 target = _getTarget();
    int[] oldValue = target.getXxx4();
    if(_getEqualsComparator().isEquals(oldValue, xxx41)) {
      return this;
    }
    target.setXxx4(xxx41);
    dispatchValueChanged(PROP_xxx4, oldValue, xxx41);
    return this;
  }

  public Student getId() {
    return _getTarget().getId();
  }

  public TestItem2 setId(Student id1) {
    TestItem2 target = _getTarget();
    Student oldValue = target.getId();
    if(_getEqualsComparator().isEquals(oldValue, id1)) {
      return this;
    }
    target.setId(id1);
    dispatchValueChanged(PROP_id, oldValue, id1);
    return this;
  }

  public Integer[] getXxx5() {
    return _getTarget().getXxx5();
  }

  public TestItem2 setXxx5(Integer[] xxx51) {
    TestItem2 target = _getTarget();
    Integer[] oldValue = target.getXxx5();
    if(_getEqualsComparator().isEquals(oldValue, xxx51)) {
      return this;
    }
    target.setXxx5(xxx51);
    dispatchValueChanged(PROP_xxx5, oldValue, xxx51);
    return this;
  }

  public int getTestItem2_5() {
    return _getTarget().getTestItem2_5();
  }

  public TestItem2 setTestItem2_5(int testItem2_51) {
    TestItem2 target = _getTarget();
    int oldValue = target.getTestItem2_5();
    if(_getEqualsComparator().isEquals(oldValue, testItem2_51)) {
      return this;
    }
    target.setTestItem2_5(testItem2_51);
    dispatchValueChanged(PROP_testItem2_5, oldValue, testItem2_51);
    return this;
  }

  public Integer getXxx2() {
    return _getTarget().getXxx2();
  }

  public TestItem2 setXxx2(Integer xxx21) {
    TestItem2 target = _getTarget();
    Integer oldValue = target.getXxx2();
    if(_getEqualsComparator().isEquals(oldValue, xxx21)) {
      return this;
    }
    target.setXxx2(xxx21);
    dispatchValueChanged(PROP_xxx2, oldValue, xxx21);
    return this;
  }

  public Student getTestItem2_1() {
    return _getTarget().getTestItem2_1();
  }

  public TestItem2 setTestItem2_1(Student testItem2_11) {
    TestItem2 target = _getTarget();
    Student oldValue = target.getTestItem2_1();
    if(_getEqualsComparator().isEquals(oldValue, testItem2_11)) {
      return this;
    }
    target.setTestItem2_1(testItem2_11);
    dispatchValueChanged(PROP_testItem2_1, oldValue, testItem2_11);
    return this;
  }

  public SparseArray<Integer> getXxx3() {
    return _getTarget().getXxx3();
  }

  public TestItem2 setXxx3(SparseArray<Integer> xxx31) {
    TestItem2 target = _getTarget();
    SparseArray<Integer> oldValue = target.getXxx3();
    if(_getEqualsComparator().isEquals(oldValue, xxx31)) {
      return this;
    }
    target.setXxx3(xxx31);
    dispatchValueChanged(PROP_xxx3, oldValue, xxx31);
    return this;
  }

  public SparseArrayPropertyEditor<? extends TestItem2, Integer> beginXxx3Editor() {
    TestItem2 target = _getTarget();
    SparseArray<Integer> values = target.getXxx3();
    if(values == null) {
      values = new SparseArray<>();
      target.setXxx3(values);
    }
    return new SparseArrayPropertyEditor<TestItem2,Integer>(target, DataMediatorDelegate.getDefault().getSparseArrayDelegate(values), PROP_xxx3, this);
  }

  @Override
  public void applyProperties(PropertyInterceptor interceptor) {
    Throwables.checkNull(interceptor);
    startBatchApply(interceptor)
      .addProperty(PROP_testItem2_2, getTestItem2_2())
      .addProperty(PROP_testItem2_3, getTestItem2_3())
      .addProperty(PROP_testItem2_6, getTestItem2_6())
      .addProperty(PROP_testItem2_4, isTestItem2_4())
      .addProperty(PROP_selected, isSelected())
      .addProperty(PROP_name, getName())
      .addProperty(PROP_xxx1, getXxx1())
      .addProperty(PROP_desc, getDesc())
      .addProperty(PROP_xxx4, getXxx4())
      .addProperty(PROP_id, getId())
      .addProperty(PROP_xxx5, getXxx5())
      .addProperty(PROP_testItem2_5, getTestItem2_5())
      .addProperty(PROP_xxx2, getXxx2())
      .addProperty(PROP_testItem2_1, getTestItem2_1())
      .addProperty(PROP_xxx3, getXxx3())
    .apply();
  }

  @Override
  public String toString() {
    return _getTarget().toString();
  }

  @Override
  public void clearProperties() {
    throw new UnsupportedOperationException("proxy class can't call this method.");
  }

  @Override
  public void recycle() {
    throw new UnsupportedOperationException("proxy class can't call this method.");
  }
}
